### Crear un nuevo usuario
POST https://api-hxge.onrender.com/api/user  HTTP/1.1
Content-Type: application/json

{
    "email": "example2Email@gmail.com",
	"password":"12341234Abc",
	"phone":"+34 123456789"
}

### Relizar un login
POST https://api-hxge.onrender.com/api/user/login  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com",
	"password":"12341234Abc"
}

### Resetear la contraseña (recibir email)
POST https://api-hxge.onrender.com/api/user/resetPassword  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com"
}

### Obtener los datos de un usuario
GET https://api-hxge.onrender.com//api/user/?id=67b708913428753374fbefad HTTP/1.1

### Editar parte o todos los datos de un usuario
PATCH  https://api-hxge.onrender.com/api/user/?id=67b708913428753374fbefad HTTP/1.1
Content-Type: application/json

{
     "email": "realEmail@gmail.com",
	"password":"12341234Abc",
	"phone":"+34 111222333"
}

### Borrar un usuario
DELETE https://api-hxge.onrender.com/api/user/?id=67b7058e22e9254ae658b074 HTTP/1.1