### Crear un nuevo usuario
POST http://localhost:3000/api/user  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com",
	"password":"12341234Abc",
	"phone":"+34 123456789"
}

### Relizar un login
POST http://localhost:3000/api/user/login  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com",
	"password":"12341234Abc",
}

### Resetear la contraseña (recibir email)
POST http://localhost:3000/api/user/resetPassword  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com",
}

### Obtener los datos de un usuario
GET http://localhost:3000/api/user/?id=67b6f9dc0ec7fb586e64c8b0 HTTP/1.1

### Editar parte o todos los datos de un usuario
PATCH  http://localhost:3000/api/user/ HTTP/1.1
Content-Type: application/json

{
    "email": "realEmail@gmail.com",
	"password":"12341234Abc",
	"phone":"+34 111222333"
}

### Borrar un usuario
DELETE http://localhost:3000/api/user/ HTTP/1.1