### Crear un nuevo usuario
POST http://localhost:3000/api/user  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com",
	"password":"12341234Abc",
	"phone":"+34 123456789"
}

### Relizar un login
POST http://localhost:3000/api/user/login  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com",
	"password":"12341234Abc"
}

### Resetear la contraseña (recibir email)
POST http://localhost:3000/api/user/resetPassword  HTTP/1.1
Content-Type: application/json

{
    "email": "exampleEmail@gmail.com"
}

### Obtener los datos de un usuario
GET http://localhost:3000/api/user/?id=67b9c2a38c90a992800e438e HTTP/1.1

### Editar parte o todos los datos de un usuario
PATCH http://localhost:3000/api/user?id=67b9c2a38c90a992800e438e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2I5YzJhMzhjOTBhOTkyODAwZTQzOGUiLCJpYXQiOjE3NDAzNDE0MzcsImV4cCI6MTc0MDM0NTAzN30.688gqsq1vFuGgapE--S5dx2kDXePwjm5kAIrkDJz5W0
Content-Type: application/json

{
    "email": "realEmail@gmail.com",
    "password": "12341234Abc",
    "phone": "+34 111222333"
}

### Borrar un usuario
DELETE http://localhost:3000/api/user/?id=67b7058e22e9254ae658b074 HTTP/1.1